### ISSUE TITLE
How to get started ?

### ISSUE THREAD

**Issue by hecperleo** [larics/pure_pursuit#8] opened 2017-07-23 13:44 UTC
Hi, i am pretty new with ROS and i want to use your pure pursuit controller. Do you have a tutorial or something like that ? I want to understand how your controller works and test it to use it on a drone simulation.

Thanks.

**Comment by dmiklic** [comment] 2017-07-25 08:36
Hi, thank you for your interest in this package.

First, a word of warning. The pure pursuit method has been developed primarily with ground vehicles in mind, so it implicitly assumes motion in the plane with three degrees of freedom (x,y,yaw) and nonholonomic constraints (differential or bicycle steering). I'm not sure how it will work with a drone. It might work under the following assumptions:

- all setpoints are constrained to the 2D plane in which the drone is initially positioned
- the drone understands how to handle Twist messages as inputs

I have a package containing some launch files which start a demo with a P3-DX navigating in Gazebo. The problem is that it depends on a path planner that we haven't open-sourced yet. However, if you are interested, I can discuss this with my colleagues and we could share the planner with you (similar restrictions apply to the planner regarding 2D assumptions).

**Comment by hecperleo** [comment] 2017-08-15 19:52
Hi, thank you for your answer. 

As you said, it should work under those assumptions. I have another package that creates a drone with few services (take off, land, go to waypoint, etc). It can handle Twist messages as inputs. My key problem is that i don't know how to make both packages work together. How to send a list of waypoints for the drone to go to them using pure pursuit. 

Is it possible to send you a mail with more details about the other package? 

Anyway, i appreciate your answer.

**Comment by dmiklic** [comment] 2017-08-20 23:27
Hi,

sorry for the delay in my reply, I was on holiday the past two weeks :) There is a planner that creates the necessary waypoints (it needs only the initial and desired vehicle configurations as inputs), it is described in more detail in [this paper](http://ieeexplore.ieee.org/document/7139465/). My colleague, who implemented the planner in ROS, has agreed to open-source the code. I'll do my best to prepare a public repo for the planner and the example code during this week.

**Comment by dmiklic** [comment] 2017-08-24 22:40
Hi VoPrak, 

I have made the planner repo public and set up a demo package for evaluating the planner and path follower [here](https://github.com/larics/lattice_navigation_demos). Try it out and see if it is useful for you. If you run into any problems, I'll be glad to help.

I've also updated the README.md with the link to the demo package (833167d982dd514dc47fac3f00ccce300f43c9a8) so i'll close this issue. Feel free to open new ones if you discover any bugs.

**Closed as completed by dmiklic** 2017-08-24 22:40 UTC
